#!/bin/sh
exec >/dev/console 2>&1
export TERM=linux
export PS1='initramfs-test:\w\$ '
stty sane
echo "made it to the rootfs! Powering down."
ip route
ifaces=$(ip route | while read a b c d e f; do
        if [[ $a = "default" ]]; then
            echo "-${e}-";
        else
            echo "$c"
        fi; done)
echo OK $ifaces > /dev/sda
#sh -i
poweroff -f
