#!/bin/bash
inst cryptsetup 
inst rmdir
inst readlink
inst umount
inst "$moddir"/cryptroot-ask.sh /sbin/cryptroot-ask
inst_hook cmdline 30 "$moddir/parse-crypt.sh"
inst_hook pre-pivot 30 "$moddir/crypt-cleanup.sh"
inst_hook pre-pivot 31 "$moddir/crypt-cleanup.sh"
inst "$moddir/crypt-lib.sh" "/lib/dracut-crypt-lib.sh"
inst /etc/crypttab
