#!/bin/bash

inst_hook pre-trigger 01 "$moddir/fips-boot.sh"
inst_hook pre-pivot 01 "$moddir/fips-noboot.sh"
inst "$moddir/fips.sh" /sbin/fips.sh
dracut_install sha512hmac rmmod insmod mount uname umount

libdir="lib"
if ldd $(find_binary sha512hmac) 2>/dev/null | grep -q /lib64/; then
    libdir="lib64"
fi

if [ -e /usr/$libdir/libsoftokn3.so ]; then
    dracut_install \
        /usr/$libdir/libsoftokn3.so /usr/$libdir/libsoftokn3.chk
else
    dracut_install \
        /$libdir/libsoftokn3.so /$libdir/libsoftokn3.chk
fi

for i in /{usr,}/$libdir/libssl.so* /{usr,}/$libdir/libcrypto.so* \
         /{usr,}/$libdir/.libssl.so*.hmac /{usr,}/$libdir/.libcrypto.so*.hmac; do
    [ -e $i ] || continue
    dracut_install $i
done

dracut_install -o /usr/$libdir/hmaccalc/sha*hmac.hmac
dracut_install fipscheck
dracut_install /etc/system-fips

if command -v prelink >/dev/null; then
    dracut_install prelink
fi

# vim:ts=8:sw=4:sts=4:et
