#!/bin/bash

_fipsmodules="aead aes_generic aes-x86_64 ansi_cprng arc4 blowfish camellia cast6 cbc ccm "
_fipsmodules+="chainiv crc32c cryptomgr crypto_null ctr cts deflate des des3_ede dm-crypt dm-mod "
_fipsmodules+="ecb eseqiv fcrypt gcm ghash_generic hmac khazad lzo md4 md5 michael_mic rmd128 "
_fipsmodules+="rmd160 rmd256 rmd320 rot13 salsa20 seed seqiv serpent sha1 sha224 sha256 sha256_generic "
_fipsmodules+="sha384 sha512 sha512_generic tcrypt tea tnepres twofish wp256 wp384 wp512 xeta xtea xts zlib"

mkdir -p "${initdir}/etc/modprobe.d"

for mod in $_fipsmodules; do
    if hostonly='' instmods $mod; then
        echo $mod >> "${initdir}/etc/fipsmodules"
        echo "blacklist $mod" >> "${initdir}/etc/modprobe.d/fips.conf"
    fi
done

# vim:ts=8:sw=4:sts=4:et
